_:
  common-upstream-kernel-test-config: &common-upstream-kernel-test-config
    job: tests
    branch: master
    identifier: "integration-upstream"
    use_internal_tf: true
    targets:
      # [NOTE] There needs to be a matching target among the Copr targets,
      # because of the default mapping and filtering (to avoid invalid values).
      # In this case (no build), it is a bug, see packit/packit-service#2841
      # Yet, the `rawhide` has no effect as there is no Copr build happening.
      fedora-rawhide-x86_64:
        distros: [Fedora-37-Updated]
      fedora-rawhide-s390x:
        distros: [Fedora-37-Updated]
      fedora-rawhide-ppc64le:
        distros: [Fedora-37-Updated]
    skip_build: true
    manual_trigger: true
    tmt_plan: kpatch-integration-upstream
    fmf_url: https://gitlab.com/redhat/centos-stream/tests/kernel/test-plans.git
    fmf_ref: main

jobs:
  - <<: *common-upstream-kernel-test-config
    # [NOTE] Runs only for PRs to be merged into `master`
    trigger: pull_request
    labels:
      - integration-pr

  - <<: *common-upstream-kernel-test-config
    trigger: commit
    labels:
      - integration-commit
