Vagrant.configure(2) do |config|
  config.vm.box = "kpatch-f22"
  config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-libvirt.box"
  config.vm.box_check_update = false

  config.vm.synced_folder "../../..", "/kpatch", type: 'rsync'

  config.vm.provision "shell", path: "vagrant-provision"

  config.vm.provider :libvirt do |domain|
    domain.memory = 2048
    domain.cpus = 8
    domain.volume_cache = 'writeback'
  end

end

# vi: set ft=ruby :
